@echo off
setlocal
cd /d "%~dp0"
set "BROWSER=%~1"
if "%BROWSER%"=="" set "BROWSER=chrome"
py -m robot --outputdir results_batch3 --variable BROWSER:%BROWSER% 045_audio_tool_offline.robot 046_load_offline.robot 047_tag_offline.robot 048_duplicate_offline.robot 049_update_propagation_on_template_import.robot 050_search_activity.robot 051_empty_animated_augment.robot 052_tag_filtering.robot 053_sort_activities.robot 054_update_propagation_offline.robot 055_sort_activities_offline.robot 056_tag_filtering_offline.robot 057_create_activity_offline_while_connected.robot 058_offline_text_edit_after_online_creation.robot 059_offline_image_after_online_creation.robot 060_offline_audio_after_online_creation.robot 061_offline_video_after_online_creation.robot 062_offline_sticker_after_online_creation.robot 063_offline_3d_object_after_online_creation.robot 064_offline_link_after_online_creation.robot 065_offline_sheet_after_online_creation.robot 066_guided_path_navigation.robot 067_remove_activity_from_path.robot 068_multi-tag-filtering.robot 069_onboarding_main.robot 070_onboarding_teacher.robot 071_onboarding_student.robot 072_onboarding_pair_association.robot 073_onboarding_search_and_find.robot 074_onboarding_information_layer.robot 075_onboarding_auto_triggered_path.robot 076_onboarding_guided_path.robot
pause
